name: local-lab-api

include:
  - ../cli/docker-compose.yml

services:
  docling-pipelines:
    build:
      context: ../..
      dockerfile: local-lab/api/Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - ../.env
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
      OPENSEARCH_USERNAME: ${OPENSEARCH_USERNAME}
      OPENSEARCH_PASSWORD: ${OPENSEARCH_PASSWORD}
      OLLAMA_HOST: http://ollama:11434
      KAFKA_BOOTSTRAP_SERVERS: kafka:29092
      DOCPIPE_DATA_PATH: /data
    volumes:
      - docling-pipelines-data:/data
    depends_on:
      - minio
      - docling-serve
      - ollama
      - opensearch
      - kafka

  kafka:
    image: apache/kafka:4.3.1
    environment:
      KAFKA_NODE_ID: "1"
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_LISTENERS: INTERNAL://:29092,CONTROLLER://:9093,EXTERNAL://:9092
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:29092,EXTERNAL://localhost:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
    ports:
      - "9092:9092"

volumes:
  docling-pipelines-data:
